### ISSUE TITLE
Bringing a Democratic Process To Node Management

### ISSUE THREAD

**Issue by jam2ja** [bitclout/backend#109]
Tonight in a club house room, ideas around Democracy within the bitclout network were discussed. 

As I understand things, the person (group of people) that creates the node in the context of this bitclout project, controls how the node is managed, maintained and updated. The NFT nodes have a lot of users, yet those users/creators have no final say in the architecture of that node. Could this change?

With todays technology it's easy to bring ideas such as Direct Democracy, and liquid Democracy to this network. 
https://en.wikipedia.org/wiki/Liquid_democracy

Why not?

-Users want to be involved in the decision making process's (changes in architecture) that effect the value of their input.
-The community is empowered when they are given the opportunity to make decision.

**Comment by maebeam** [comment]
Hi! Please create a discussion here so other users can chime in: https://github.com/bitclout/cips/discussions

**Comment by jam2ja** [comment]
no worries, have moved.
