### ISSUE TITLE
user doesn't meet the min 0.0007 BTC requirement if they deposited it in small chunks

### ISSUE THREAD

**Issue by andrewarrow** [bitclout/backend#13]
I ran into this error:

https://github.com/bitclout/frontend/blob/bbb70b0c1018f882b8915ae56e6998f0c5210c29/src/app/buy-bitclout-page/buy-bitclout/buy-bitclout.component.ts#L124

from:

https://github.com/bitclout/backend/blob/96d24569a7b4581644a330be168c441c948d9040/routes/transaction.go#L561

<img width="394" alt="45" src="https://user-images.githubusercontent.com/127054/119540390-3f27db80-bd42-11eb-947a-d7ac3579037e.png">

This all worked fine when I re-did it with another new account, but this time sent the BTC all in one tx.

**Comment by maebeam** [comment]
Unfortunately there's nothing we can do to resolve this. Every deposit increases the size of the transaction.
