### ISSUE TITLE
How to use Bitclout in local?

### ISSUE THREAD

**Issue by natalialinov** [bitclout/backend#138]
Hello, I installed the Bitclout project in my local. But in the beginning I didn't know where to add money to my account. How can I do that? I want to test local bitclout.

**Comment by AdityaChaudhary0005** [comment]
@natalialinov do you want to run your own node or just the frontend?

If the latter, then follow this tutorial I had written once https://devsclout.hashnode.dev/running-bitclouts-frontend-for-local-development-without-running-node-ckqtfj0ia0n1rjcs1ckrsgv0n

**Comment by natalialinov** [comment]
@AdityaChaudhary0005 I want to run my own node. I want to do some testing on it. Do you have a faucet to test on your node?

**Comment by AdityaChaudhary0005** [comment]
I am not a node runner, but I hope the official docs can help you https://docs.bitclout.com/code/dev-setup

**Comment by natalialinov** [comment]
I did the ones here. I initialized backend,identity and frontend. But I could not load the test token into my wallet.

**Comment by AikonMishima** [comment]
@natalialinov - feel free to join the discord https://discord.gg/bitclout and go to channel “nodes”.
We could resolve your issue swiftly there.

**Comment by natalialinov** [comment]
@AikonMishima Thank you. I asked the question in the group and I am waiting for an answer.

**Comment by maebeam** [comment]
Closing this as there's not a specific issue needing to be fixed here.

**Comment by Forpee** [comment]
@tijno Are you still lending your node?

**Comment by tijno** [comment]
sure feel free to connect on discord
