### ISSUE TITLE
HELP: Setting up dev environment

### ISSUE THREAD

**Issue by MUFYAheer** [bitclout/backend#18]
I'm using arch linux and trying to set up the dev environment as [described here](https://docs.bitclout.com/code/dev-setup).
When I try to run `./n0_test` I get the following error
```
Failed to execute process './n0_test'. Reason:
exec: unknown error (errno was 8)
The file './n0_test' is marked as an executable but could not be run by the operating system.
```
Can some please help me how I can build `n0_test` from source

**Comment by thehappypenguin** [comment]
You could try running `chmod +x n0_test`

**Comment by thehappypenguin** [comment]
or add debugging to the file (adding `set -x`)and make sure you're running it with bash

**Comment by maebeam** [comment]
It's missing a shebang. Feel free to submit a PR

**Comment by MUFYAheer** [comment]
Thanks for the clearification. I've submitted a PR  #31
