### ISSUE TITLE
Failing to run the new backend image - backend exited with code 0

### ISSUE THREAD

**Issue by kanshi** [bitclout/backend#3]
I replicated this with a fresh download of run repository. The backend image simply shuts down.

Shouldn't there be an ENTRYPOINT in the new backend image?

**Comment by casbeebc** [comment]
There seeems to be an ENTRYPOINT within [test.Dockerfile](https://github.com/bitclout/backend/blob/main/test.Dockerfile) but not in the main [Dockerfile](https://github.com/bitclout/backend/blob/main/Dockerfile)
