### ISSUE TITLE
I can not update profile picture (gif). I also know about only png and jpeg supported, but I want to use also gif.

### ISSUE THREAD

**Issue by Dipesh0822** [bitclout/backend#32]

**Comment by tijno** [comment]
My guess is that its probably a design decision not to have animated profile pictures on bitclout.com.

**Comment by maebeam** [comment]
Thanks for the suggestion. Unfortunately, GIFs are rather large files and we store user avatars on the blockchain itself. Because of the file size limitations we have chosen not to support GIFs at this time.

**Comment by maebeam** [comment]
Thanks for the suggestion. Unfortunately, GIFs are rather large files and we store user avatars on the blockchain itself. Because of the file size limitations we have chosen not to support GIFs at this time.
