### ISSUE TITLE
Add Breaks in Profile Description

### ISSUE THREAD

**Issue by harpreet9629** [bitclout/backend#43]
Add Breaks in Profile Description in Api.
Cause in api when profile data fetch everything in one single line.
Please fix that.
![Screenshot_1](https://user-images.githubusercontent.com/26606638/121743521-19ab1800-cb1f-11eb-9b12-9b8205238f95.jpg)

**Comment by AdityaChaudhary0005** [comment]
@harpreet9629 This isn't true at all. The API returns profile description with line breaks where required
Here is what I get when I fetch my profile description:

`"Description": "17 year young | Programmer | Illustrator\n\nFounder: @DevsClout\n\nDev @knowyourclout \u27a1\ufe0f @RugPullAlert \u27a1\ufe0f @GlobalClout\n\nDiscord: https://discord.gg/ggvtTje "`

You can clearly see '\n' in the description.

**Comment by maebeam** [comment]
You'll need to turn the newlines into HTML breaks when you render descriptions
