### ISSUE TITLE
After updating to new version node is not downloading blocks after block 25779

### ISSUE THREAD

**Issue by donhardman** [bitclout/backend#6]
Get error

```
E0519 16:29:27.914707       1 Yfh0cFoF.go:1] AddBitCloutMessage: Not enqueueing message GET_HEADERS because peer is disconnecting
E0519 16:29:32.966301       1 Yfh0cFoF.go:1] AddBitCloutMessage: Not enqueueing message GET_HEADERS because peer is disconnecting
```

Tried to remove everything and relaunch. Anyway stuck same place and not load new blocks.

Build from source of release 1.0.0

```bash
backend run --data-dir=/data --txindex=1 --target-outbound-peers=16 --max-inbound-peers=64 --add-seeds=bitclout-seed-2.io,bitclout-seed-4.io
```

How to debug this and find the reason? Ports are open, have outbound peers.

**Comment by donhardman** [comment]
Tried to put read-only mode and get the same issue but another error.

```
I0520 11:16:05.441568       1 server.go:1171] Server._handleBlock: Received block ( 25876 / 26101 ) from Peer [ Remote Address: 35.232.92.5:17000 PeerID=37 ]
W0520 11:16:05.441992       1 server.go:1237] Got duplicate block <Header: < 25876, 00000000000279775ca9ee5dc64ec1a77a88ab2a1ee93e71559cf67ed9e4ab36, 1 >, Signer Key: BC1YLhULV1UBa7gYxEttkLdtzzkvXBwmgmyPKgJaGs35g2tiPafA2hv> from peer [ Remote Address: 35.232.92.5:17000 PeerID=37 ]
I0520 11:16:05.743858       1 server.go:1171] Server._handleBlock: Received block ( 25877 / 26101 ) from Peer [ Remote Address: 35.232.92.5:17000 PeerID=37 ]
W0520 11:16:05.744266       1 server.go:1237] Got duplicate block <Header: < 25877, 00000000000118d895b9e5b41bb64f7b6311eec7f18be6e4e4617c3dbcf67dbd, 1 >, Signer Key: BC1YLhULV1UBa7gYxEttkLdtzzkvXBwmgmyPKgJaGs35g2tiPafA2hv> from peer [ Remote Address: 35.232.92.5:17000 PeerID=37 ]
```

And it repeats all the time and nothing changes. Just infinity loop

Looks like this one is the reason. How to fix it? 

Tried to remove all and relaunch many times.

**Comment by donhardman** [comment]
OK I have found the problem

Looks like some bitcoin tx was processed and added to blockchain but disappeared from bitcoin blockchain or whatever. Please check it.


```
I0520 12:34:45.148979       1 server.go:1171] Server._handleBlock: Received block ( 25780 / 26108 ) from Peer [ Remote Address: 35.232.92.5:17000 PeerID=1 ]
E0520 12:34:45.187608       1 blockchain.go:1073] MarkBlockInvalid: Block height: 25780, Block hash: 0000000000035dbf7210093e16d6ffcd69e21c09fa4b4f4120306a99b42ee3a1, Error: ConnectBlock: : ConnectTransaction: : RuleErrorBitcoinExchangeBlockHashNotFoundInMainBitcoinChain
E0520 12:34:45.187630       1 blockchain.go:1074] MarkBlockInvalid: Printing stack trace so error is easy to find:
E0520 12:34:45.188221       1 blockchain.go:1075] goroutine 182 [running]:
runtime/debug.Stack(0xc0000ac000, 0x2, 0x1)
	/usr/lib/go/src/runtime/debug/stack.go:24 +0x9f
github.com/bitclout/core/lib.(*Blockchain).MarkBlockInvalid(0xc0008dca50, 0xc0fc722c80, 0xc1662003f0, 0x61)
	/core/lib/blockchain.go:1075 +0x192
github.com/bitclout/core/lib.(*Blockchain).ProcessBlock(0xc0008dca50, 0xc18ef61a10, 0xc02af3de00, 0x0, 0x0, 0x0)
	/core/lib/blockchain.go:1772 +0xd74
github.com/bitclout/core/lib.(*Server)._handleBlock(0xc0008dc9a0, 0xc0fd53c000, 0xc18ef61a10)
	/core/lib/server.go:1217 +0x3c6
github.com/bitclout/core/lib.(*Server)._handlePeerMessages(0xc0008dc9a0, 0xc194976620)
	/core/lib/server.go:1494 +0x137
github.com/bitclout/core/lib.(*Server).messageHandler(0xc0008dc9a0)
	/core/lib/server.go:1542 +0x215
created by github.com/bitclout/core/lib.(*Server).Start
	/core/lib/server.go:1725 +0xbd
E0520 12:34:45.188230       1 blockchain.go:1082] MarkBlockInvalid: Not marking blocks invalid for now because it makes debugging easier
```

**Comment by 2000c5** [comment]
Had this issue as well (as I see on Discord most are)...

If you delete your node data and try a fresh resync it will fail at block #7651 every time and not go beyond that.

E0520 14:47:50.001408   29894 blockchain.go:1073] MarkBlockInvalid: Block height: 7651, Block hash: 000000000055e730dfdd449306fd8a94aaa4d09f612d34ba288022331346c391, Error: ConnectBlock: : ConnectTransaction: : **RuleErrorBitcoinExchangeBlockHashNotFoundInMainBitcoinChain**
E0520 14:47:50.001437   29894 blockchain.go:1074] MarkBlockInvalid: Printing stack trace so error is easy to find:

**Comment by donhardman** [comment]
Well

There is bitcoin exchange: c8e202fed8f725fb2ef76144208dcd06e76626019eb0c7d6fc827cae3792a848

It was processed in block 25780

https://explorer.cloutangel.com/tx/3JuETs6RYdLQiJjBSmMKqkgxmJHER6EiqJ4qARCAYKqr4FC9g8seqr80

Bitcoin exchange info
Bitcoin tx: c8e202fed8f725fb2ef76144208dcd06e76626019eb0c7d6fc827cae3792a848
Address: 1DVfu1SVqPS3Vg89Tu11PuQynYYXVzCnCD
Burned: 0.00465332 BTC
Credited: 1.245000394 Bitclout
Before: 8398011.889128121 Bitclout
After: 8398013.134128515 Bitclout

Checking in BTC: we have this one (still in mempool)
Checking in Blockcypher: they do not have that tx

But because of you use blockcypher now all node is broken.

**Comment by 2000c5** [comment]
FYI: Bitcoin transaction is valid.

Bitclout Hash: 000000000055e730dfdd449306fd8a94aaa4d09f612d34ba288022331346c391

BTC Transaction ID: 2a2c6486d8f1909c578650f7199446a6c11b43108113ec1f483347fb82f84d7e

Amount: 0.01674809 BTC

**Comment by donhardman** [comment]
![image](https://user-images.githubusercontent.com/59067742/118983200-5ebbae80-b9a6-11eb-9b5c-45f6dfcd481b.png)
![image](https://user-images.githubusercontent.com/59067742/118983226-6713e980-b9a6-11eb-86b6-f9ad279dc3f1.png)

**Comment by diamondhands0** [comment]
This should be fixed now. Some code cleanup caused this issue; very sorry about that.
