### ISSUE TITLE
ProfilePic missing on api responses

### ISSUE THREAD

**Issue by gpmarchi** [bitclout/backend#60]
Hi there,

I've been using a couple of profile endpoints from the backend api and I've noticed you guys removed the ProfilePic property from the responses (such an example is this endpoint: https://bitclout.com/api/v0/get-single-profile).

How can I get the profile pictures now that they are not being included in the responses anymore?

**Comment by maebeam** [comment]
https://bitclout.com/api/v0/get-single-profile-picture/BC1YLi6LpXTemAG8T9ptyWAkMywrjynwZcKjB5DkDXxrsG5kgAwAqxq
