### ISSUE TITLE
Captcha completely broke my application

### ISSUE THREAD

**Issue by BogdanDidenko** [bitclout/backend#63]
When trying to create a transaction "/api/v0/send-bitclout"
I received a 403 error in response with a proposal to pass the captcha, but the essence of my application is that it sends funds by itself.
![unknown](https://user-images.githubusercontent.com/11133686/123703514-25137880-d86d-11eb-9595-32045085940b.png)
My application is not working.
Apparently, it's not just me who has problems:
https://bitclout.com/posts/6bd9b0749c3e9043de56556ff9bf240fe7735516f3475d7fbf29075e28cea4c1

Add please https://signing-cloutmegazord.web.app/ and https://cloutmegazord.com/ to some whitelist.

**Comment by maebeam** [comment]
While we do recommend running your own node, I will remove the captcha from this endpoint.
