### ISSUE TITLE
cant sync full blocks after height 7650 - running from source code ./n0

### ISSUE THREAD

**Issue by dgsus** [bitclout/backend#8]
E0519 13:58:42.299696    6411 blockchain.go:1073] MarkBlockInvalid: Block height: 7651, Block hash: 000000000055e730dfdd449306fd8a94aaa4d09f612d34ba288022331346c391, Error: ConnectBlock: : ConnectTransaction: : RuleErrorBitcoinExchangeBlockHashNotFoundInMainBitcoinChain

**Comment by dgsus** [comment]
covered by 

https://github.com/bitclout/backend/issues/6

**Comment by diamondhands0** [comment]
This should be fixed now. Some code cleanup caused this issue; very sorry about that.
