### ISSUE TITLE
Block 35460, transaction 1635 - missing fields BlockHashHex and TransactionMetadata

### ISSUE THREAD

**Issue by starykolarz** [bitclout/backend#81]
[block 35460 full.txt](https://github.com/bitclout/backend/files/6831131/block.35460.full.txt)
[block 35460, transactions 1635-1636.txt](https://github.com/bitclout/backend/files/6831132/block.35460.transactions.1635-1636.txt)

I'm processing the blockchain for some ideas I'm playing with. In the process of importing to a db, I found a transaction - block 35460, id 1635 (actually - the id is not there, as metadata is missing, but it's also not duplicated) - that is returned incorrectly from /api/v1/block output.

The problem: missing fields BlockHashHex and TransactionMetadata

I'm running my node from current docker image.

Request below (from SoapUI, but same thing happens using other methods, for example c# HttpClient):

POST http://myinternalip:17001/api/v1/block HTTP/1.1
Accept-Encoding: gzip,deflate
Content-Type: application/json
Content-Length: 57
Host: myinternalip:17001
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.5 (Java/12.0.1)

{
	"Height": 35460,
	"HashHex": "",
	"FullBlock": true
}

I'm submitting, as I don't know go yet ;-) and I don't know the codebase enough to be able to verify, if it's a sign of some obscure problem.

I'll add to this issue if I find other anomalies when processing subsequent blocks.

**Comment by tijno** [comment]
This happens when your TXINDEX is not fully in sync.

**Comment by starykolarz** [comment]
I ran it on a few outbound nodes that mine is connected to - and you're right, on those nodes it's ok.

Is it posiible to resync only a specific block on a node, without reprocesing fro day 0?

**Comment by tijno** [comment]
No. Have to restart if stuck

**Comment by maebeam** [comment]
Yeah, sounds like your txindex is not synced correctly. Apologies for the weirdness. I'm in the process of rewriting TXIndex entirely.
