### ISSUE TITLE
Not able to run testnode , issue with h2non/bimg vips package

### ISSUE THREAD

**Issue by amar71094** [bitclout/backend#84]
# github.com/h2non/bimg
/tmp/go-build459570334/b338/_x005.o: In function `vips_reduce_bridge':
../../../go/pkg/mod/github.com/h2non/bimg@v1.1.5/vips.h:132: undefined reference to `vips_reduce'
collect2: error: ld returned 1 exit status
# github.com/h2non/bimg
In file included from ../../../go/pkg/mod/github.com/h2non/bimg@v1.1.5/vips.go:5:0:
../../../go/pkg/mod/github.com/h2non/bimg@v1.1.5/vips.h: In function ‘vips_reduce_bridge’:
../../../go/pkg/mod/github.com/h2non/bimg@v1.1.5/vips.h:132:9: warning: implicit declaration of function ‘vips_reduce’ [-Wimplicit-function-declaration]
  return vips_reduce(in, out, xshrink, yshrink, NULL);

Is this some comaptibility issue of libvips with go1.15.6?
Please help

**Comment by maebeam** [comment]
What OS are you running? This issue might be better posted in the bimg repo

**Comment by amar71094** [comment]
I am using Ubuntu 16.04 LTS (xenial). Looked for it in the bimg repo didn`t found anything. Still looking
Actually vips library require GO v1.3+ , whereas bitclout documentation asks to install v1.15.6.
Now I am getting this error , after upgrading to Go v1.6 
cannot find package "github.com/bitclout/backend/cmd" in any of:
	/usr/local/go/src/github.com/bitclout/backend/cmd (from $GOROOT)

**Comment by maebeam** [comment]
Go 1.3 and 1.6 are outdated, you need at least 1.15

**Comment by amar71094** [comment]
Yeah , I am getting the error "undefined reference to 'vips_reduce'  in go version 1.15.6 , so thought of downgrading it, but that didn`t work too.

**Comment by amar71094** [comment]
I got it working. Thanks for help.
Actually there was a problem occuring due to libvips v8.2. It is not compatible with a subpackage in libvips (imgproxy)
I have now upgraded to libvips v8.12.0 and now my Bitclout node is running,

**Comment by maebeam** [comment]
Glad to hear it
